### ISSUE TITLE
As a google sheets user, I want a spreadsheet generated that matches the agreed upon data model and fields for tracking PEMM manuscript data, so that I can import and add project data.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/pemm-scripts#1]
# testing notes
we can test this by starting to enter the first few entries from the macomber text file. note that we are shifting validation-related stuff to #8 .

# dev notes
## all
<s>allow resize permissions for all locked fields</s>
apparently, this is impossible: [google support forum question](https://support.google.com/docs/forum/AAAABuH1jm0Dd-xrFT_BAM/?hl=nl)
we will just need to set the sizing beforehand, or alternatively designate an "admin" editor (Wendy?) who can edit all fields regardless of protection.
## collections
- [x] switch order of "institution" and "abbreviation"
## manuscript
- [x] remove validation on "latitude" Sorry, this was listed in the wrong place; it should be under collection, and it was not done.
- [x] remove validation on "century"
- [x] remove validation on "date range start" and "date range end"
- [x] autogenerate "number of stories" from story instance sheet
- [x] create autogenerated locked column "name"; see below comment for format
- [x] create column "link"
## story origin
- [x] remove "european" boolean
- [x] add multiselect field "region" with values ["africa", "europe", "levant", "other"]
## canonical story
- [x] remove validation on macomber id
- [x] remove non-european origin
- [x] remove validation on incipit column
- [x] incipit source should be restricted to "name" on manuscript
## story instance
- [x] add canonical story id column
- [x] add canonical story title column
- [x] remove validation on folio fields
- [x] remove page reproduction column
- [x] make "confidence score" a dropdown with values "high/medium/low"
- [x] make "manuscript" pull from name field on manuscript

**Comment by thatbudakguy** [comment]
- manuscripts get a "name" column that is autogenerated in the format `HMML (EMML) 23)` (institution-collection abbrev-id)
- incipit source pulls from this field.
- story instance - manuscript also pulls from this field.

**Comment by elambrinaki** [comment]
"Collection" sheet: 
- allow a resize permission for the "Name" column
- Switch the order of "Institution" and "Abbreviation" columns: abbreviation is the second column, institution is the third column; the name formatting remains the same: Institution (Abbreviation)
- "Latitude" field: the data validation is wrong

"Manuscript" sheet:
- "Total Folios" and "Total pages": only numbers allowed
- "Century" column: problem with validation. In addition, for an exact century, the formatting should be "number.00"
- "Date Range Start" and "Date Range End" columns: validation doesn't work
- "Number of Stories": the value should be automatically generated from the Story Instances sheet
- add a column "Name" linked to Institution and Abbreviation from the "Collection" sheet
- Move "Page Reproduction" and "Link" columns from "Story Instances" here

"Story Origin" sheet:
- In the second column, instead of a check-box, make a drop-down list with four options: Europe, Africa, Levant, none of the above. Name the column "Region".

"Canonical Story" sheet:
- "Macomber ID": should allow a number and a letter
- get rid of "Non-European Origin" column
- "Incipit" column: data validation shouldn't be applied here 
- "Incipit Source": after adding Manuscript name column, this column would be in a form [Institution (Abbreviation) number], where Institution (Abbreviation) is the manuscript name, and the number is the manuscript ID 

"Story Instance" sheet:
- add "Canonical Story ID" and "Canonical Story Title" columns
- "Folio" column: not working
- "Page Reproduction" column: to delete
- "Link" column: move to Manuscript sheet
- "Order in Manuscript" column: autogenerated
- "Confidence Score": a drop-down list high/medium/low

**Comment by rlskoeser** [comment]
Note: logic for autogenerating Order in Manuscript is not implemented at this time (it's not a simple calculation, since it has to include folio as well as line and column); do not include it when testing this feature.

**Comment by WendyLBelcher** [comment]
### Comments from testing

Okay, re "Collection" sheet:

- allow a resize permission for the "Name" column (this is not yet done; it won't allow you to expand it so you can see what is there)

- "Latitude" and Longitude field:   it actually does let you put them both in decimal form, so that's good. But the data validation message comes up anyways and is wrong. It is asking for degree input. Can you change the validation for these two fields to decimal system for latlong, e.g., 51.519410, -0.127144? And then the Validation should say "Must be a valid longitude between ..." and "Must be a valid latitude between ..." I'm not sure what the numbers should say.

That's all I see for Collections sheet.

**Comment by elambrinaki** [comment]
Globally, can we make column expansion automatic? (adjusting the width of the columns depending on the content)

"Manuscript" sheet:

- "Century" field: format [two digits_dot_00/25/50/75] (to prohibit 5.25 for instance; the century number is a two-digit number)
- "Date Range End" number should be greater than "Date Range Start" number
- Did we decide to delete "Page Reproduction" field? It has been moved from "Story Instances", but hasn't been added here

**Comment by elambrinaki** [comment]
"Story Origin" sheet:

- Can we add a third column, "Country", in case the country is known (e.g., Europe in the column "Region", and France in the third column "Country")? 

The drop down of countries listed there should be
France
Germany
Italy
Spain
Belgium
Poland
Russia
Israel
Syria
Egypt
Ethiopia
Other

**Comment by WendyLBelcher** [comment]
Re Story Origin third column of "Country." The drop down of countries listed there should be
France
Germany
Italy
Spain
Belgium
Poland
Russia
Israel
Syria
Egypt
Ethiopia
Other

**Comment by elambrinaki** [comment]
"Story Instance" sheet:

- "Column end" value should exceed the "Column start" value
- The same for the "Line end" and "Line start"
- Incipit field: needs to be the broadest to make typing easier

**Comment by WendyLBelcher** [comment]
In the Story Instance sheet, they will spend the most time in the "Incipit" field, where they will be typing in fidel and matching and going back and forth between it and the manuscript. It will take time. That field, therefore, should be much broader, so they can see at least half of what they have typed. Maybe it could be expanded to four or five times it's current breadth.

**Comment by WendyLBelcher** [comment]
We don't recall why Story Origin was separated out as a sheet. We think it would be better to have its columns of Region and now Country appear on the Canonical Story sheet. That way, the person entering can see the title while entering the information. So, for instance, the first one on the Canonical Story sheet there now is Macomber 1-A, Theophilius of Alexandria. So, one would just go over several columns and click on the drop down in Region of "Africa" and in Country of "Egypt." And be done.

**Comment by WendyLBelcher** [comment]
Story Origin--add a City column as well as the country. No validation on city.

**Comment by elambrinaki** [comment]
Re using Hamburg database:

- Their "Manuscript" sheet has information we need for PEMM "Manuscript" sheet
- Their "Institutions" sheet corresponds to PEMM "Collection" sheet
- If we import information from Hamburg "Institutions" sheet, we might need to add more columns to match theirs, e.g. "Note" column ("formerly part of the British Museum")
- "Title" in Hamburg "Institutions" sheet = "Institution" in PEMM "Collection" sheet

**Comment by elambrinaki** [comment]
Everything else works great

**Comment by thatbudakguy** [comment]
since only validation-related issues remain; closing this as per discussion at 12/5 mtg.
